export const GENDER_SHOW_RESET = 'GENDER_SHOW_RESET'
export const GENDER_SHOW_SET_ERROR = 'GENDER_SHOW_SET_ERROR'
export const GENDER_SHOW_SET_RETRIEVED = 'GENDER_SHOW_SET_RETRIEVED'
export const GENDER_SHOW_TOGGLE_LOADING = 'GENDER_SHOW_TOGGLE_LOADING'
