export const GENDER_DELETE_RESET = 'GENDER_DELETE_RESET'
export const GENDER_DELETE_SET_ERROR = 'GENDER_DELETE_SET_ERROR'
export const GENDER_DELETE_SET_DELETED = 'GENDER_DELETE_SET_DELETED'
export const GENDER_DELETE_TOGGLE_LOADING = 'GENDER_DELETE_TOGGLE_LOADING'
