export const SKILL_SHOW_RESET = 'SKILL_SHOW_RESET'
export const SKILL_SHOW_SET_ERROR = 'SKILL_SHOW_SET_ERROR'
export const SKILL_SHOW_SET_RETRIEVED = 'SKILL_SHOW_SET_RETRIEVED'
export const SKILL_SHOW_TOGGLE_LOADING = 'SKILL_SHOW_TOGGLE_LOADING'
