export const SKILL_DELETE_RESET = 'SKILL_DELETE_RESET'
export const SKILL_DELETE_SET_ERROR = 'SKILL_DELETE_SET_ERROR'
export const SKILL_DELETE_SET_DELETED = 'SKILL_DELETE_SET_DELETED'
export const SKILL_DELETE_TOGGLE_LOADING = 'SKILL_DELETE_TOGGLE_LOADING'
